# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sun Jul 20 14:20:03 2014
#      by: pyside-uic 0.2.14 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.playerName = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.playerName.setFont(font)
        self.playerName.setObjectName("playerName")
        self.verticalLayout_2.addWidget(self.playerName)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playerName_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.playerName_2.setFont(font)
        self.playerName_2.setObjectName("playerName_2")
        self.horizontalLayout.addWidget(self.playerName_2)
        self.playerName_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.playerName_7.setFont(font)
        self.playerName_7.setObjectName("playerName_7")
        self.horizontalLayout.addWidget(self.playerName_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(478, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playerName_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.playerName_3.setFont(font)
        self.playerName_3.setObjectName("playerName_3")
        self.horizontalLayout_3.addWidget(self.playerName_3)
        self.playerName_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.playerName_5.setFont(font)
        self.playerName_5.setObjectName("playerName_5")
        self.horizontalLayout_3.addWidget(self.playerName_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playerName_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.playerName_4.setFont(font)
        self.playerName_4.setObjectName("playerName_4")
        self.horizontalLayout_2.addWidget(self.playerName_4)
        self.playerName_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.playerName_6.setFont(font)
        self.playerName_6.setObjectName("playerName_6")
        self.horizontalLayout_2.addWidget(self.playerName_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.hotelTab = QtGui.QWidget()
        self.hotelTab.setObjectName("hotelTab")
        self.buildHotelButton = QtGui.QPushButton(self.hotelTab)
        self.buildHotelButton.setGeometry(QtCore.QRect(10, 270, 111, 22))
        self.buildHotelButton.setObjectName("buildHotelButton")
        self.hotelList_2 = QtGui.QTableView(self.hotelTab)
        self.hotelList_2.setGeometry(QtCore.QRect(10, 40, 761, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotelList_2.sizePolicy().hasHeightForWidth())
        self.hotelList_2.setSizePolicy(sizePolicy)
        self.hotelList_2.setShowGrid(True)
        self.hotelList_2.setObjectName("hotelList_2")
        self.pushButton_3 = QtGui.QPushButton(self.hotelTab)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 380, 81, 22))
        self.pushButton_3.setObjectName("pushButton_3")
        self.hotelList = QtGui.QLabel(self.hotelTab)
        self.hotelList.setGeometry(QtCore.QRect(10, 13, 751, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.hotelList.setFont(font)
        self.hotelList.setStyleSheet("")
        self.hotelList.setObjectName("hotelList")
        self.tabWidget.addTab(self.hotelTab, "")
        self.tabBank = QtGui.QWidget()
        self.tabBank.setObjectName("tabBank")
        self.tabWidget.addTab(self.tabBank, "")
        self.tabStock = QtGui.QWidget()
        self.tabStock.setObjectName("tabStock")
        self.tabWidget.addTab(self.tabStock, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_Simulation = QtGui.QAction(MainWindow)
        self.actionNew_Simulation.setObjectName("actionNew_Simulation")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew_Simulation)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        #QtCore.QObject.connect(self.buildHotelButton, QtCore.SIGNAL("clicked()"), self.hotelList.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Investment Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.playerName.setText(QtGui.QApplication.translate("MainWindow", "Player_Name", None, QtGui.QApplication.UnicodeUTF8))
        self.playerName_2.setText(QtGui.QApplication.translate("MainWindow", "Time Elapsted:", None, QtGui.QApplication.UnicodeUTF8))
        self.playerName_7.setText(QtGui.QApplication.translate("MainWindow", "1 year", None, QtGui.QApplication.UnicodeUTF8))
        self.playerName_3.setText(QtGui.QApplication.translate("MainWindow", "Money:", None, QtGui.QApplication.UnicodeUTF8))
        self.playerName_5.setText(QtGui.QApplication.translate("MainWindow", "$100", None, QtGui.QApplication.UnicodeUTF8))
        self.playerName_4.setText(QtGui.QApplication.translate("MainWindow", "Time Left:", None, QtGui.QApplication.UnicodeUTF8))
        self.playerName_6.setText(QtGui.QApplication.translate("MainWindow", "1 year", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.buildHotelButton.setText(QtGui.QApplication.translate("MainWindow", "Build New Hotel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Build Hotel", None, QtGui.QApplication.UnicodeUTF8))
        self.hotelList.setText(QtGui.QApplication.translate("MainWindow", "Hotel List", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hotelTab), QtGui.QApplication.translate("MainWindow", "Hotels", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBank), QtGui.QApplication.translate("MainWindow", "Bank", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStock), QtGui.QApplication.translate("MainWindow", "Stocks", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Simulation.setText(QtGui.QApplication.translate("MainWindow", "New Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))